### ISSUE TITLE
[Bug] [Upload] Permettre de modifier une ligne lors d'une erreur dans l'upload, pour un individu connu.

### ISSUE THREAD

**Issue by ClaireCasu** [gip-inclusion/rdv-insertion#1953]
**Comportement observé**
Situation rencontrée lors de l'import du fichier de ARCHER AIP - le 10 avril avec Quentin et Samantha.

On peut voir qu'on est sur un usager connu (le matching s'est bien fait) car on voit le bouton "**Ajouter à cette organisation**" 
Lorsqu'une ligne est en erreur lors de l'upload, nous avons la possibilité de modifier une information en double cliquant sur la case problématique (par exemple: l'adresse mail qui comporte un ,com au lieu d'un .com). 

Lorsque je modifie, je peux valider et puis j'ai une erreur "**404 utilisateur n'existe pas**".
L'unique moyen de réaliser l'import est de modifier l'adresse mail sur le fichier excel, ensuite ça marche.

Autrement dit : _si matching fait mais création impossible/attribut incohérent avec ce qu'on a en base, impossible de modifier avec erreur 404 utilisateur n'existe pas_

**Comportement souhaité**
Pouvoir modifier la ligne et que l'ajout à l'organisation fonctionne.

**Comment by Michaelvilleneuve** [comment]
@ClaireCasu Idem à nouveau j'ai pas réussi à reproduire, j'ai eu le même cas décrit (utilisateur trouvé, bouton ajouter à cet organisation) avec un mail "salma.betagouv+demomassconj@gmail,com"
<img width="1219" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/cec6725d-0d21-4db0-be13-a404441ac100">

J'ai modifié le mail pour mettre .com au lieu de ,com et cette fois c'est bien passé comme sur le screeshot 🙈

**Comment by ClaireCasu** [comment]
@Michaelvilleneuve J'ai pu reproduire suite à la démo que j'ai faite ce matin.
Tu peux te connecter en **démo** sur le 60 (60 - Démo générique RDV-I) et essayer de charger le fichier en PJ dans l'orga Pôle Parcours.
J'ai modifié l'adresse de Claire test1 et Eva test3  et quand je double clique pour modifier l'adresse mail, je retrouve l'erreur 404.
[Fichier_FT.xlsx](https://github.com/betagouv/rdv-insertion/files/14979409/Fichier_FT.xlsx)

**Comment by ClaireCasu** [comment]
Test avec le fichier en PJ, sur Pole Parcours test CD (CD 60 en démo)
Erreur quand je modifie le mail suivant : claire.casubolo+test15042024@beta.Gouv,fr
