### ISSUE TITLE
[Tech] Unscope les routes qui n'ont pas besoin d'être scopés

### ISSUE THREAD

**Issue by aminedhobb** [gip-inclusion/rdv-insertion#2103]
Suite de [cette discussion](https://github.com/betagouv/rdv-insertion/pull/2071) et de celle abordée en point tech pour le scopage des routes.
Je serais assez chaud de partir sur l'idée que @Michaelvilleneuve a suggéré: 

* Unscoper la création/suppression de ressources qui ne le nécessite pas
* Restocker le niveau de navigation en session
* Avoir une méthode qui redirige vers la bonne page avec la navigation en session, et si cette info n'est pas présente rediriger vers une page par défaut (niveau départemental avec alerte sentry par exemple ?)

**Comment by qblanc** [comment]
je suis pas sûr d'être d'accord avec la partie en session. je serais plus favorable à ce qu'on s'appuie sur le `request.referer` pour récupérer le bon niveau de navigation (puisque les routes "navigables" seront toujours scopées)

**Comment by Michaelvilleneuve** [comment]
Je suis pas hyper chaud non plus chaud pour l'avoir en session c'est super chiant quand on dépend d'une session pour pleins de trucs, c'est toujours un peu caché une sessions, voilà plutôt ce que j'imaginais : 
On permet de passer :department_id et :organisation_id en param get
`DELETE /archives/1?department_id=3`
Si le param existe on set la current_structure, s'il y est pas on fallback sur le referer
```ruby
def structure_user_path(user_id)
   if current_structure_type.present?
     send(:"#{current_structure_type}_user_path", { id: user_id, **structure_id_param, **params })
   else
     request.referer
   end
end
```
Je pense qu'en faisant la refacto de meta-programming du navigation_helper on pourrait en profiter pour rajouter une logique automatique pour ça 

Si on était dans le contexte d'une SPA je pense que ça ferait sens d'avoir la donnée department ID et organisation ID dans des headers HTTP custom. Plus flexible qu'une session car setté non pas par le backend mais par le front, plus visible car en clair dans les header. 
Mais bon modifier avoir des headers custom sur des balises "a href" c'est pas idéal ^^

**Comment by aminedhobb** [comment]
> On permet de passer :department_id et :organisation_id en param get
DELETE /archives/1?department_id=3

Ok et du coup ton lien pour delete une archive ton lien ce serait `archives_path(**structure_id_param)` ? Pourquoi je pense que je préfère peut-être cette solution au `request.referer`.

> Mais bon modifier avoir des headers custom sur des balises "a href" c'est pas idéal ^^

Oui non peut-être pas ^^

**Comment by Michaelvilleneuve** [comment]
Pour delete ça serait plutôt ça : 
```
archive_path(archive.id, **structure_id_param) # pour être redirigé au bon endroit
archive_path(archive.id) # pour fallback sur le `referer` ou simplement pour les cas où on a besoin de redirection (page upload ?)
```
