### ISSUE TITLE
[Tests] Certains tests échouent en local 

### ISSUE THREAD

**Issue by aminedhobb** [gip-inclusion/rdv-insertion#2172]
Lié à cette discussion sur mattermost: https://mattermost.incubateur.net/betagouv/pl/eijtzyhna7rfdkcn8gnb6sedwo

Certains changements ne sont pas appliqués en local lorsqu'on lance les tests et ne s'appliquent qu'après avoir lancé manuellement la commande  `RAILS_ENV=test rails assets:precompile`.

Il faudrait trouver un moyen pour que les te

**Comment by Michaelvilleneuve** [comment]
Impossible pour moi de reproduire le bug, je me dé-assigne en attendant
