### ISSUE TITLE
[Suppression d'orgas] Supprimer des organisations du Vaucluse qui ne seront plus utilisées

### ISSUE THREAD

**Issue by SalmaBennani** [gip-inclusion/rdv-insertion#2174]
Dans le Vaucluse, il n'y a plus le marché SSP, le CD reprend l'organisation du RSA. Les organisations actuelles qui étaient donc du marché ne sont plus d'actualité, ils veulent les supprimer.

Il faudrait donc supprimer les organisations avec les ID rdv-solidarités suivants : 

- 2426
- 3358
- 3348
- 3351
- 3356
- 3352
- 3357
- 3349
- 3353
- 3355
- 3350

**Comment by Michaelvilleneuve** [comment]
Comme évoqué ce matin : les AgentRole ont été supprimé côté RDVI et RDVSP
