### ISSUE TITLE
[RDV-SP] Empêcher la modification de la catégorie d'un motif lorsque celui-ci est déjà rattaché à des rdvs

### ISSUE THREAD

**Issue by aminedhobb** [gip-inclusion/rdv-insertion#2214]
Aujourd'hui rien n'empêche de changer la catégorie d'un motif alors même que des rdvs sont rattachés à ce motif.
Il faudrait rajouter une condition à [cette validation](https://github.com/betagouv/rdv-service-public/blob/73582622720776a6d5836245c6ab84f8f9dcef1f/app/models/motif.rb#L263) pour empêcher ça

### Motivations 

Aujourd'hui, un usager peut avoir plusieurs suivis (ressource `follow_up`). Chaque suivi est lié à une catégorie de motif.
Lorsqu'une participation est créé pour l'usager, on la lie à un suivi de l'usager. Le suivi est choisi via la catégorie de motif pour lequel le rdv a été pris. 
Ainsi, si on permet de changer la catégorie de motif sur un motif, les participations resteront attachées aux suivis sur la catégorie de motif d'origine, ce qui créerait des incohérences. 
Si la catégorie est renseignée sur un motif alors qu'il n'avait pas de catégorie renseigné, le problème est moins grave puisque les rdvs/participations existantes ne sont pas rattachés à de suivi dans ce cas-là.

**Comment by victormours** [comment]
Merci pour la clarification !
Vu qu'on a aussi les mairies qui peuvent ajouter ou enlever des catégories de motifs, c'est pas sûr que ça soit possible de faire cette modification, donc j'aimerais bien mieux comprendre le contexte pour trouver quelque chose qui arrange tout le monde.

En essayant de comprendre dans quels cas on pourrait avoir des changements de catégories de motif, et j'imagine que c'est possible que ça soit une manière de corriger une erreur. Est-ce que le scénario suivant vous semble plausible ?

- En tant qu'admin de territoire ou d'organisation, je crée un nouveau motif intitulé "RDV Régulation Direct'emploi - France Travail"
- Par inattention, je l'associe à la catégorie de motif "RSA orientation - travailleurs indépendants", alors que j'aurais du la lier à "RSA orientation - coaching emploi"
- Les première invitations partent, et des rdv sont planifiés
- Avant que le premier rdv n'ai lieu, je remarque mon erreur
- Je souhaite donc changer la catégorie de motif pour corriger mon erreur

Par ailleurs, est-ce qu'il y a d'autre types de scénarios qui pourraient amener à un changement de catégorie de motif ?

**Comment by aminedhobb** [comment]
> Est-ce que le scénario suivant vous semble plausible ?

* Ce scénario est possible mais je pense que c'est rare: en plus de la configuration au niveau du motif dans rdvsp, il faut mettre en place en place une configuration au niveau du suivi dans rdvi (avec le message d'invitation adéquat), donc il faudrait se tromper aux 2 endroits. 

* De plus les messages d'invitations seront des invitations sur "RSA orientation - travailleurs indépendants". Donc placer le rdv à postériori dans une autre catégorie me semble trompeur.

* Aussi, si on change la catégorie, il faut mettre en place la configuration pour la nouvelle catégorie sur rdvi également. Et vu le problème initiale (les rdvs restent liés aux suivis sur "RSA orientation - travailleurs indépendants"), ils devront garder leur configuration pour "RSA orientation - travailleurs indépendants" pouvoir voir les rdvs précédemment pris. Dans ce cas la meilleure solution est de nous contacter pour qu'on fasse toute la manoeuvre plutôt que de changer directement sur le motif. 


Après je comprends que vous vouliez garder de la flexibilité si vous pensez utiliser les catégories comme "étiquette" sur les mairies sans toute la logique que l'on met derrière côté rdvi. On en avait pas forcément conscience de ça au moment de faire ce ticket. Dans ce cas-là on peut réfléchir à des solutions de notre côté (comme par exemple mettre une alerte quand ça arrive).

**Comment by aminedhobb** [comment]
Pour info j'ai demandé à l'équipe produit et ils m'ont remonté une fois où c'est arrivé dans le Tarn. Dans ce cas on a dû justement faire une migration pour changer la catégorie de tous les suivis associés aux rdvs en plus du motif.

@victormours si vous pensez que c'est trop restrictif côté rdvsp pour les utilisations futures des catégories de motifs (ce qui est tout à fait entendable) on peut partir sur une autre solution.

**Comment by victormours** [comment]
C'est intéressant, dans le cas du Tarn pourquoi est-ce qu'il y a eu un changement de catégorie de motif ?
Plus précisément : est-ce que le changement essayait de corriger une erreur, ou est-ce que le changement en question était une erreur ?

**Comment by aminedhobb** [comment]
Vu en point hebdo le 23/07: 

* On ne met pas de condition de validation au niveau du motif côté rdvsp
* On met une alerte chez nous si un motif change de catégorie (je dirais Sentry + Mattermost) et qu'il a des rdvs associés
* Si on voit qu'il y a beaucoup d'occurrences, on pourra éventuellement mettre un warning lors de l'édition du motif

Du coup @Michaelvilleneuve je pense qu'on peut fermer la PR côté rdv-sp et en ouvrir une nouvelle côté rdv-i.
