### ISSUE TITLE
[Super-Admin] - Mettre un bandeau super-admin en haut des écrans rdvi

### ISSUE THREAD

**Issue by samanthaauffret** [gip-inclusion/rdv-insertion#2255]
**Contexte**
- En tant que super-admin, je ne me rend pas bien compte que je suis connecté "en tant que X" sur l'interface RDVI. Le bandeau blanc sous le header, trop discret, peut être oublié.

**Parcours actuel**
Le parcours peut être compliqué et risqué pour le super-admin. Il peut par inadvertance, faire des actions sur les comptes agents en pensant être sur son compte.
[Parcours actuel sur figma](https://www.figma.com/proto/vDCDHdMjNe4mxkoSC2A5J3/Maquettes?node-id=1-4&t=BLzzElhJWLmLrc5W-9&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A4&show-proto-sidebar=1)

**Nouveaux écrans et nouveau parcours**
- Sortir le CTA super-admin du header, pour retrouver un header identique à n'importe quel utilisateur (CTA "Besoin d'aide ?")
- Créer un bandeau de couleur en haut de l'écran, dédié au super-admin
- Ce bandeau est affiché par défaut sur tous les écrans rdv-i et peut être masqué et réaffiché à l'aide d'un petit CTA à droite du bandeau (cf. maquettes)
- Créer 2 états du bandeau : un état connecté au super-admin et un état déconnecté du super-admin. 
- Depuis ce bandeau, indiquer textuellement si l'utilisateur est connecté au super-admin rdvi ou non
- Depuis ce bandeau, permettre à l'utilisateur de revenir à l'interface du super-admin ou de revenir à sa session rdv-i. 

[Nouveau parcours super-admin sur Figma](https://www.figma.com/proto/vDCDHdMjNe4mxkoSC2A5J3/Maquettes?node-id=5-1311&t=HRRx2hWAOdA5UAdR-9&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1311&show-proto-sidebar=1)

**Captures**

Header déconnecté / ouvert
![Image](https://github.com/user-attachments/assets/b05ea68f-7b9d-45dc-92f3-aac0a010aab7)

Header connecté / ouvert
![Image](https://github.com/user-attachments/assets/3761a8c0-044b-4e64-aa22-d916801185be)

Header deconnexion / ouvert
![Image](https://github.com/user-attachments/assets/95620edf-76b9-4040-b115-358c5acc04af)

**Comment by Michaelvilleneuve** [comment]
> [@Michaelvilleneuve](https://github.com/Michaelvilleneuve) [@samanthaauffret](https://github.com/samanthaauffret) J'ai quelques retours après avoir utilisé de ce bandeau que je fais ici :) . Dites-moi ce que vous pensez de ces retours (soit ici soit à l'oral), et peut-être qu'on pourra voir si on prend un ticket pour ajuster si vous pensez que c'est nécessaire.
> 
> ## Retours techniques
> Techniquement, je me rends compte que si je coche l'option pour cacher le bandeau, les choses suivantes se passent:
> 
> * Lorsque je hard refresh la page, il y a un glitch un peu gênant où le bandeau apparait puis disparait
> * Lorsque je soumets un formulaire (par exemple lorsque j'archive un dossier), le bandeau réapparait alors que l'option pour le cacher est inchangée
> 
> ## Retours design
> Ressenti purement personnel: Lorsque je ne suis pas loggé "en tant que", j'ai un peu de mal avec la phrase "Bonjour Amine, voulez-vous accéder au SuperAdmin ?". Je trouve qu'elle prend de la place et qu'elle fait trop remarquer le bandeau que l'on voudrait plus discret, pour les démos notamment. Et je trouve qu'elle n'est pas indicative et répétitive avec le bouton "Accéder au super-admin". Enfin je trouve la formule "Bonjour" un peu bizarre entre nous 😄 .
> 
> J'imagine que ça a été fait pour avoir une mise en page analogue à l'état où on est "loggé en en tant que .." ce que je comprends très bien, mais je me demande si ce ne serait quand même pas mieux sans. Je pense que je préférerais sans personnellement.

@aminedhobb Désolé j'avais vu ce commentaire et je n'ai pas pris le temps de répondre 🙏 . Merci pour tes retours, je vais voir pour corriger effectivement c'est gênant s'il ré-apparait.  

Mais sinon pour ton retour global et sur le design je reviens sur ce que l'on s'est dit sur le ticket pour les webhook côté superadmin et ce qu'on s'était dit en dm : 
Je pense qu'il faut pas oublier qu'on est sur des features destinées uniquement à nous en interne. Notre objectif doit être de se concentrer sur les agents et leur expérience à eux. 

Certes si on a des quick win ou des choses qui peuvent nous faciliter la vie tant mieux mais utiliser notre temps de dev et de design pour débattre de détails d'implémentations techniques ou de subtilités UX pour des features internes ne me semble pas une priorité. 

Il faut qu'on privilégie toujours quelque chose simple à implémenter, simple à maintenir avec un bon compromis en terme d'efficacité UX

**Comment by aminedhobb** [comment]
Je suis d'accord sur le fait de ne pas perdre trop de temps là-dessus (pour moi ce n'est pas le même sujet que le webhook ceci dit ou ce n'était pas une question purement design :) ), mais comme je l'ai dit ça apparait en démo et en ça ça peut être affectant.
Aussi je ne trouve pas ça négligeable d'avoir une bonne expérience utilisateur soi-même quand on est sur l'appli. En tous cas je suis prêt à faire un petit effort personnellement pour l'améliorer :)

**Comment by samanthaauffret** [comment]
@aminedhobb  
Pour le retour design sur la phrase "bonjour Amine, voulez-vous accéder au SuperAdmin". 
Je comprend que ça peut-être perturbant de se vouvoyer soit même. En revanche je trouve le "bonjour" plutôt sympa ! ça peut même donner un côté "logiciel convivial" en démo.

La présence du prénom a tout de même une utilité pour renforcer le fait que tu es bien sur ton espace et pas loggué "en tant que". la phrase créé un équilibre visuel entre la gauche et la droite. 
Après je suis d'accord avec @Michaelvilleneuve sur le fait qu'on peut garder le bandeau en l'état, avec la phrase de gauche, vu que c'est juste pour nous.

**Comment by aminedhobb** [comment]
Merci @samanthaauffret pour les arguments 👍 , je n'avais pas vu la chose de cette façon, je comprends mieux. 
Comme je l'ai dit c'était un ressenti purement personnel donc pas de soucis pour le garder comme ça si c'est ce qui est préféré.

Sur le glitch et le souci post formulaire, je vais quand même créer une issue qu'on pourra prendre un jour si on a du temps, c'est clairement pas urgent.
