### ISSUE TITLE
[CD83] - Rendre non annulable tous les motifs des organisations VAR INSERTION

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2302]
Ticket suite à une demande du département il y a déjà 2 ans de rendre non annulables par les usagers tous les motifs du CD83 concernant les organisations rdv_insertion, il faudrait faire de même pour tous les nouveaux motifs.

**Comment by aminedhobb** [comment]
[Fait pour la catégorie "RSA - Reconnect" ](https://mattermost.incubateur.net/betagouv/pl/cdy884dywt8hzbw8fc46mk81qr)
