### ISSUE TITLE
[SMS/Mail] Mieux formatter les numéros de tel dans les SMS

### ISSUE THREAD

**Issue by aminedhobb** [gip-inclusion/rdv-insertion#2309]
Les numéros des organisations et des lieux ne sont pas formatés lorsqu'ils ont entrés en BDD.
Du coup nous envoyons ces numéros non formatés avec des caractères qui peuvent allonger et/ou réduire la visibilité (par exemple `01.11.22.33.44` ou `01.11.22.33.44`  comme numéro de contact dans nos sms/mails d'invitations et de convocations.

**Comment by Michaelvilleneuve** [comment]
Vu avec Amine, finalement pas tant de formats étranges dans la base de données et nous n'avons pas le contrôle sur l'entrant de rdvs donc on laisse tel quel. 
Juste quelques occurrences bizarre que je vais discuter avec Eva.
Je ferme le ticket.
