### ISSUE TITLE
[Usagers] Supprimer tous les usagers orga id 456

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2331]
Suite à des tests et une erreur d'import l'organisation ALI Drancy - id 456 souhaite supprimer tous les bénéficiaires importés pour recommencer et refaire un import dans la bonne catégorie.

SUPPRIMER TOUS LES USAGERS QUI N'ONT PAS DE RDV SVP.

**Comment by aminedhobb** [comment]
@Evajuliab c'est que c'est pour les usagers qui n'ont pas eu un rdv ? C'est pas précisé sur le ticket.

**Comment by Evajuliab** [comment]
@aminedhobb je viens d'avoir l'info, il faut delete tous les usagers même ceux avec des RDV, ce sont des tests ou erreurs. En revanche il ya des RDV collectifs déjà planifiés, on les laisse, merci :)

**Comment by Evajuliab** [comment]
@aminedhobb je MAJ le ticket il faut supprimer que les usagers qui n'ont aucun rdv associés, merci :pray:
