### ISSUE TITLE
[**CSV PDI**] Générer un export csv des usagers pour la PDI

### ISSUE THREAD

**Issue by aminedhobb** [gip-inclusion/rdv-insertion#2348]
En vu des travaux d'harmonisation des bases de la PDI, Charles et Victor auraient besoin d'un export de la base usagers de rdv-i pour la croiser avec celles des emplois.
Les données de la base des emplois avec lesquels ils vont les croiser sont les suivants: 
`first_name`,`last_name`,`email`,`phone`,`birthdate`,`ID France Travail`,`Code pays INSEE`,`Code ville INSEE`.

Du coup notre export devrait comporter les colonnes suivantes de la table `users`: 

`first_name`, `last_name`, `email`, `phone_number`, `birth_date`, `france_travail_id`, `address`,  et éventuellement la colonne `city_code` du record associé dans la table `address_gecodings`.

Le CSV devra être envoyé à Charles via Bitwarden Send avec l'option de le télécharger qu'une seule fois.

**Comment by Michaelvilleneuve** [comment]
CSV envoyé, reçu et traité par Charles 👍
