### ISSUE TITLE
[Statistiques] - Cleaner les stats publiques en prod du CD71

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2351]
Après des tests effectués en amont, le CD71, démarrage prévu le 14/10 souhaite que les invitations envoyées en prod pour tester et qui apparaissent dans l'onglet statistiques de notre footer soit remis à zéro.

![Image](https://github.com/user-attachments/assets/f6d551ab-52f6-4d74-9a6c-f5a5f7b66191)

**Comment by Evajuliab** [comment]
@Michaelvilleneuve ils ont déjà démarré le 8/10 finalement donc ce serait bien de pouvoir enlever les invitations envoyées avant cette date, merci :)

**Comment by Michaelvilleneuve** [comment]
34 invitations supprimées toutes crées entre Mai et le 8 Octobre 2024
