### ISSUE TITLE
[LANDING PAGE] - Ajouts des CTA "acquisition"

### ISSUE THREAD

**Issue by samanthaauffret** [gip-inclusion/rdv-insertion#2376]
**Contexte**
Accélération de l'acquisition. 70 départements ciblés. 
La landing page va être de plus en plus consultée par les départements qui n'utilisent pas encore rdvi. Mais les CTA actuels ne sont pas assez mis en avant 

**L'idée**
En solution QuickWin, rediriger les personnes intéressées vers Hugo grâce à l'ajout de 3 CTA sur la landing page, dans le header et dans le bloc au-dessus de la ligne de flottaison. 

**Détail de la solution**
Positionner les 2 CTA, situés sous la phrase d'accroche H1 du site : 
- **Un CTA "Être rappelé" :** il renvoi vers le même formulaire tally [LIEN DU FORMULAIRE](https://tally.so/r/nGJo0k) (cc @hugo-smn ) 
- **Un CTA "Découvrir un cas utilisateur" :** il renvoie vers cette page : https://rdv-insertion.gitbook.io/guide-dutilisation-rdv-insertion-and-faq/blog. 

Lien de la maquette : https://www.figma.com/design/ImrCdy0RLn7k2YzefjSAcw/Site-vitrine?node-id=2-46&t=gUwiRBTFajjWa9Os-4

**Comment by Holist** [comment]
@samanthaauffret la phrase en dessous du titre a changé dans la maquette en lien.
Initialement c'était : "rdv-insertion permet aux départements et aux structures d'insertion d'organiser facilement leurs rendez-vous (individuels, collectifs, entretiens d'embauche, suivi RSA,...)"
Est ce que je prend celle de la maquette dans ce ticket tant que j'y suis vu que ce n'est pas spécifié dans l'issue.

**Comment by hugo-smn** [comment]
@Holist le lien du tally https://tally.so/r/nGJo0k
Merci pour ta patience !
