### ISSUE TITLE
[Webhooks - BDR] Ne pas envoyer de webhooks de destruction pour rgpd

### ISSUE THREAD

**Issue by aminedhobb** [gip-inclusion/rdv-insertion#2400]
Les webhooks envoyés pour des destructions de rdvs pour cause de RGPD ne sont pas traités par les BDR et renvoie des erreurs.
Il faudrait ne pas envoyer de webhooks pour ces raisons à ce département

**Comment by Holist** [comment]
Actuellement je ne vois pas rien dans le job de suppression rgpd qui pourraient permettre de remonter l'info du type de suppression (rgpd ou non) dans le payload des webhook. Est ce une feature à mettre en place ? Ou alors ce sont tout les webhook de suppression de rdv que l'on ne doit pas envoyer au 13 ?
