### ISSUE TITLE
[Landing Page] Changer vidéo démo

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2435]
Video de démo à actualiser sur la landing page rdv-insertion.
Dispo sur le [drive sur ce lien ](https://drive.google.com/drive/my-drive?dmr=1&ec=wgc-drive-globalnav-goto)

Il faut uploader la vidéo sur scaleway + mettre à jour le lien sur la landing.

**Comment by Michaelvilleneuve** [comment]
Vidéo mise à jour sur le site
