### ISSUE TITLE
[Catégorie] - enlever les usagers d'une catégorie

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2492]
Demande de l'ALI DRANCY après erreur d'import ils souhaitent desaffecter tous les usagers de la catégorie "RSA INFORMATION D'INTEGRATION" pour recommencer un import et pouvoir commencer à utiliser l'outil et envoyer des invitations aux bonnes personnes 

Organisation id 456 (RDVI) 
motif_category_id=12 

J'ai mis en P1 car ça les bloque pour pouvoir commencer

**Comment by Holist** [comment]
C'est fait. J'ai enlevé les suivi de la catégorie de motif en question pour les usagers de l'organisation (194 usagers au total)
