### ISSUE TITLE
[RDV] Enlever possibilité d'annuler le RDV d'orientation CD50

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2499]
La Manche a un pré-requis est que l'usager ne puisse pas annuler son RDV d'orientation. A priori ça avait été vu avec Rémi à l'époque et je leur avais confirmé dans un mail de juillet23 que leurs rdvs étaient en effet non annulables 

-> Ils sont pro invitations mais veulent absolument que l'usager appelle la hotline pour annuler son RDV s'il est indispo pour en recaler un autre avec lui dans la foulée et ne pas le convoquer et rentrer dans l'orientation en - de 15 jours (c'est le cas aujourd'hui) 

**Orga ID RDVI 14 - Plateforme orientation Manche** 

Motifs concernés : (id RDVS)
- 11195
- 25197
- 25198
- 11196

**Comment by Holist** [comment]
J'ai vérifié le motif 11195 et 11196 sont déjà non annulable par les usagers.
Pour les 2 autres c'était effectivement pas le cas, je viens de faire le changement.

**Comment by Holist** [comment]
Je confirme donc que tout les motifs de la liste ici sont non annulable et non editable par les usagers (sauf bug ?)

**Comment by Evajuliab** [comment]
@Holist merci ! en effet les 2 motifs que tu cites n'étaient pas ouverts à l'invitation donc c'est niquel 👍
