### ISSUE TITLE
[Supprimer usagers CD971]

### ISSUE THREAD

**Issue by Evajuliab** [gip-inclusion/rdv-insertion#2515]
A la demande du CD971, ils veulent supprimer les listes des bénéficiaires importés lors de l'XP SPIE sur rdv-insertion entre août et décembre 23 sur les organisations suivantes : 

- Conseil départemental Guadeloupe ID 83 RDVI
- Mission Locale 971 ID 84 RDVI
- CAF 971 ID 85 RDVI

**Comment by Michaelvilleneuve** [comment]
C'est fait 👍
